/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// See https://docusaurus.io/docs/site-config for all the possible
// site configuration options.

// List of projects/orgs using your project for the users page.
const users = [
  {
    caption: 'Docusaurus: Pemeliharaan situs web dokumentasi.',
    // You will need to prepend the image path with your baseUrl
    // if it is not '/', like: '/test-site/img/image.jpg'.
    image: '/wika-guide/img/docusaurus_logo.svg',
    infoLink: 'https://docusaurus.io/en/',
    pinned: true,
  },
  {
    caption: 'algolia: Dukungan fitur pencarian yang handal.',
    image: '/wika-guide/img/algolia_logo_only.svg',
    infoLink: 'https://community.algolia.com/docsearch/',
    pinned: true,
  },
  {
    caption: 'diagrams.net: Dukungan pembuatan flowchart.',
    image: '/wika-guide/img/drawio_logo_only.svg',
    infoLink: 'https://www.diagrams.net/',
    pinned: true,
  },
  {
    caption: 'unDraw: Dukungan gambar ilustrasi.',
    image: '/wika-guide/img/undraw_logo.svg',
    infoLink: 'https://undraw.co/',
    pinned: true,
  },
  {
    caption: 'React: Pustaka antarmuka pengguna.',
    image: '/wika-guide/img/react_logo.svg',
    infoLink: 'https://reactjs.org/',
    pinned: true,
  },
  {
    caption: 'Tables Generator: Mempermudah pembuatan tabel markdown.',
    image: '/wika-guide/img/tablesgenerator_logo.svg',
    infoLink: 'https://www.tablesgenerator.com/markdown_tables',
    pinned: true,
  },
];

const siteConfig = {
  title: 'Juklak User', // Title for your website.
  tagline: 'Panduan penggunaan aplikasi WIKA.',
  url: 'https://faizadi.github.io', // Your website URL
  baseUrl: '/wika-guide/', // Base URL for your project */
  // For github.io type URLs, you would set the url and baseUrl like:
  //   url: 'https://facebook.github.io',
  //   baseUrl: '/test-site/',

  // Used for publishing and more
  projectName: 'wika-guide',
  organizationName: 'faizadi',
  // For top-level user or org sites, the organization is still the same.
  // e.g., for the https://JoelMarcey.github.io site, it would be set like...
  //   organizationName: 'JoelMarcey'

  // For no header links in the top nav bar -> headerLinks: [],
  headerLinks: [
    // Links to document with id doc1 for current language/version
    { doc: "toc", label: "Dokumen" },
    // Link to page found at pages/en/help.js or if that does not exist, pages/help.js, for current language
    // { page: "help", label: "Help" },
    // Links to href destination, using target=_blank (external)
    // { href: "https://github.com/", label: "GitHub", external: true },
    // Links to blog generated by Docusaurus (${baseUrl}blog)
    { blog: true, label: "Blog" },
    // Determines search bar position among links
    { search: true },
    // Determines language drop down position among links
  // { languages: true }
  ],

  // If you have users set above, you add it here:
  users,

  /* path to images for header/footer */
  headerIcon: 'img/wika_logo_white.png',
  footerIcon: 'img/wika_logo_square.png',
  favicon: 'img/wika_logo_square.png',

  /* Colors for website */
  colors: {
    primaryColor: '#3366BB',
    secondaryColor: '#3A5B91',
  },

  /* Custom fonts for website */
  /*
  fonts: {
    myFont: [
      "Times New Roman",
      "Serif"
    ],
    myOtherFont: [
      "-apple-system",
      "system-ui"
    ]
  },
  */

  // This copyright info is used in /core/Footer.js and blog RSS/Atom feeds.
  copyright: `Copyright © ${new Date().getFullYear()} WIKA - Departemen Sistem Informasi`,

  algolia: {
    apiKey: '446c126b3a9af0207d75a15ecfe69c45',
    indexName: 'wika-guide',
  },

  highlight: {
    // Highlight.js theme to use for syntax highlighting in code blocks.
    theme: 'dracula',
  },

  markdownPlugins: [
    function foo(md) {
      md.core.ruler.enable([
        'abbr'
      ]);
      md.block.ruler.enable([
        'footnote',
        'deflist'
      ]);
      md.inline.ruler.enable([
        'footnote_inline',
        'ins',
        'mark',
        'sub',
        'sup'
      ]);
    },
  ],

  // Add custom scripts here that would be placed in <script> tags.
  scripts: [
    'https://buttons.github.io/buttons.js',
    'https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js',
    '/wika-guide/js/code-block-buttons.js',
  ],
  stylesheets: ['/css/code-block-buttons.css'],

  // On page navigation for the current documentation page.
  onPageNav: 'separate',
  // No .html extensions for paths.
  cleanUrl: true,
  scrollToTop: true,

  blogSidebarCount: 'ALL',
  blogSidebarTitle: { default: 'Tulisan Terbaru', all: 'Semua Tulisan' },

  facebookAppId: '735549226943374',
  facebookComments: true,
  twitter: 'true',
  twitterUsername: 'ptwijayakarya',

  // Open Graph and Twitter card images.
  ogImage: 'img/undraw_online.svg',
  twitterImage: 'img/undraw_tweetstorm.svg',

  // For sites with a sizable amount of content, set collapsible to true.
  // Expand/collapse the links and subcategories under categories.
  // docsSideNavCollapsible: true,

  // Show documentation's last contributor's name.
  enableUpdateBy: true,

  // Show documentation's last update time.
  enableUpdateTime: true,

  // You may provide arbitrary config keys to be used as needed by your
  // template. For example, if you need your repo's URL...
  repoUrl: 'https://github.com/faizadi/wika-guide',
};

module.exports = siteConfig;
